### ISSUE TITLE
Checking out a fresh FFCRM instance and running rake db:create throws an error

### ISSUE THREAD

**Issue by steveyken** [fatfreecrm/fat_free_crm#1120]
Steps to reproduce:

1. Checkout FFCRM master from git
2. Run `bundle install`
3. Run `rake db:create`

Get the following error (truncated to FFCRM relevant parts):

```
~/code/ffcrm/fat_free_crm(master)ruby-2.7.3$ rake db:create
rake aborted!
ActiveRecord::NoDatabaseError: connection to server at "127.0.0.1", port 5432 failed: FATAL:  database "fat_free_crm_development" does not exist
...
~/code/ffcrm/fat_free_crm/lib/fat_free_crm/fields.rb:27:in `field_groups'
~/code/ffcrm/fat_free_crm/lib/fat_free_crm/fields.rb:35:in `fields'
~/code/ffcrm/fat_free_crm/lib/fat_free_crm/fields.rb:39:in `serialize_custom_fields!'
~/code/ffcrm/fat_free_crm/lib/fat_free_crm/fields.rb:19:in `has_fields'
~/code/ffcrm/fat_free_crm/app/models/entities/lead.rb:70:in `<class:Lead>'
~/code/ffcrm/fat_free_crm/app/models/entities/lead.rb:41:in `<main>'
...
~/code/ffcrm/fat_free_crm/app/models/observers/lead_observer.rb:9:in `<class:LeadObserver>'
~/code/ffcrm/fat_free_crm/app/models/observers/lead_observer.rb:8:in `<main>'
...
~/code/ffcrm/fat_free_crm/config/environment.rb:12:in `<main>'
...
~/.rvm/gems/ruby-2.7.3/gems/railties-6.1.7/lib/rails/application.rb:533:in `block in run_tasks_blocks'
~/.rvm/gems/ruby-2.7.3/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
~/.rvm/gems/ruby-2.7.3/bin/ruby_executable_hooks:22:in `eval'
~/.rvm/gems/ruby-2.7.3/bin/ruby_executable_hooks:22:in `<main>'

```

**Comment by steveyken** [comment]
This happens because there is a circular dependency during application load in the fields.rb file. 

There is code to serialize custom fields during application load, but this code depends on the database existing in order to find out which fields to serialize.

I have a patch that will fix this and will submit shortly.
