### ISSUE TITLE
Error runnign migration 20230526212613_convert_to_active_storage.rb

### ISSUE THREAD

**Issue by steveyken** [fatfreecrm/fat_free_crm#1122]
Steps to reproduce:

1. git clone ffcrm...
2. bundle install
3. rake db:create
4. rake db:migrate

I get the following error (truncated):

```
== 20230526211831 CreateActiveStorageTables: migrating ========================
-- create_table(:active_storage_blobs, {:id=>:primary_key})
   -> 0.0217s
-- create_table(:active_storage_attachments, {:id=>:primary_key})
   -> 0.0273s
-- create_table(:active_storage_variant_records, {:id=>:primary_key})
   -> 0.0218s
== 20230526211831 CreateActiveStorageTables: migrated (0.0713s) ===============

== 20230526212613 ConvertToActiveStorage: migrating ===========================
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

wrong number of arguments (given 1, expected 2..3)
~/code/ffcrm/fat_free_crm/db/migrate/20230526212613_convert_to_active_storage.rb:18:in `prepare'
~code/ffcrm/fat_free_crm/db/migrate/20230526212613_convert_to_active_storage.rb:18:in `up'
...
```

**Comment by steveyken** [comment]
Seems related to erronous ActiveStorage migration guide code in PaperClip - https://github.com/thoughtbot/paperclip/issues/2603

Potential solution: https://github.com/thoughtbot/paperclip/pull/2568#issuecomment-381629629

**Comment by johnbumgardner** [comment]
What database are you using to get this?

**Comment by steveyken** [comment]
postgresql, will check which version

**Comment by johnbumgardner** [comment]
ugh i tested the active storage migration on sqlite and mysql, shouldve checked pg too :/

**Comment by ferrisoxide** [comment]
I'm not sure if this is useful, but this is a hacky change that at least the migration runs - though without prepare statements unfortunately.

```ruby
    ActiveRecord::Base.connection.raw_connection.then do |conn|
      unless conn.is_a?(PG::Connection)
        ActiveRecord::Base.connection.raw_connection.prepare(<<-SQL)
          INSERT INTO active_storage_blobs (
            `key`, filename, content_type, metadata, byte_size, checksum, created_at
          ) VALUES (?, ?, ?, '{}', ?, ?, ?)
        SQL

        ActiveRecord::Base.connection.raw_connection.prepare(<<-SQL)
          INSERT INTO active_storage_attachments (
            name, record_type, record_id, blob_id, created_at
          ) VALUES (?, ?, ?, #{get_blob_id}, ?)
        SQL
      end
    end
```

**Comment by nelsonmatenda** [comment]
I went through the same error. I tested both with postgres and mysql and I always have some error to do this migration

**Comment by ferrisoxide** [comment]
Can this be closed now #1137 is in `master`?

**Comment by cchavez** [comment]
Hi all.

Not sure if anyone noticed, this migration didn't take in count the Avatars.
