### ISSUE TITLE
Missing action_text_rich_texts table

### ISSUE THREAD

**Issue by chalmagean** [fatfreecrm/fat_free_crm#1262]
Migrations fail due to missing `action_text_rich_texts` table.

```
== 20230526211831 CreateActiveStorageTables: migrated (0.0327s) ===============

== 20230526212613 ConvertToActiveStorage: migrating ===========================
-- transaction(nil)
rails aborted!
StandardError: An error has occurred, this and all later migrations canceled: (StandardError)

PG::UndefinedTable: ERROR:  relation "action_text_rich_texts" does not exist
LINE 9:  WHERE a.attrelid = '"action_text_rich_texts"'::regclass
                            ^
~/Work/fat_free_crm/db/migrate/20230526212613_convert_to_active_storage.rb:51:in `block (2 levels) in up'
~/Work/fat_free_crm/db/migrate/20230526212613_convert_to_active_storage.rb:50:in `each'
~/Work/fat_free_crm/db/migrate/20230526212613_convert_to_active_storage.rb:50:in `block in up'
~/Work/fat_free_crm/db/migrate/20230526212613_convert_to_active_storage.rb:49:in `up'

Caused by:
ActiveRecord::StatementInvalid: PG::UndefinedTable: ERROR:  relation "action_text_rich_texts" does not exist (ActiveRecord::StatementInvalid)
LINE 9:  WHERE a.attrelid = '"action_text_rich_texts"'::regclass
                            ^
~/Work/fat_free_crm/db/migrate/20230526212613_convert_to_active_storage.rb:51:in `block (2 levels) in up'
~/Work/fat_free_crm/db/migrate/20230526212613_convert_to_active_storage.rb:50:in `each'
~/Work/fat_free_crm/db/migrate/20230526212613_convert_to_active_storage.rb:50:in `block in up'
~/Work/fat_free_crm/db/migrate/20230526212613_convert_to_active_storage.rb:49:in `up'

Caused by:
PG::UndefinedTable: ERROR:  relation "action_text_rich_texts" does not exist (PG::UndefinedTable)
LINE 9:  WHERE a.attrelid = '"action_text_rich_texts"'::regclass
                            ^
~/Work/fat_free_crm/db/migrate/20230526212613_convert_to_active_storage.rb:51:in `block (2 levels) in up'
~/Work/fat_free_crm/db/migrate/20230526212613_convert_to_active_storage.rb:50:in `each'
~/Work/fat_free_crm/db/migrate/20230526212613_convert_to_active_storage.rb:50:in `block in up'
~/Work/fat_free_crm/db/migrate/20230526212613_convert_to_active_storage.rb:49:in `up'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

**Comment by CloCkWeRX** [comment]
https://stackoverflow.com/questions/56708362/pgundefinedtable-error-relation-action-text-rich-texts-does-not-exist-ra

**Comment by gacurl** [comment]
the fix referenced above didn't clear the issue at my end. Currently TS and will update note.

**Comment by cchavez** [comment]
I have the same issue with the migration and running the suggested action didn't fix the issue.

**Comment by cchavez** [comment]
Hi all, I found that the table is created in some migration on the branch 0.20.1, not sure why is not part of the migration in master or the other branches.

**Comment by cchavez** [comment]
> Hi all, I found that the table is created in some migration on the branch 0.20.1, not sure why is not part of the migration in master or the other branches.

Hi all.

I'm not sure what is the correct way to run the migrations because I was in the branch **0.22.x** and after the migration run fails what I did was checkout the **0.20.1** branch and run the command:

`RAILS_ENV=production bundle exec rake db:migrate`

because if you run the task

`RAILS_ENV=production bundle exec rake action_text:install`

It will create a migration for **active_storage** and it will create conflict because it will complain that there is already another migration for active_storage.

I wonder if in some release notes there is information about that migrations.
