### ISSUE TITLE
Caused by: NameError: uninitialized constant ConvertToActiveStorage::PG (NameError)

### ISSUE THREAD

**Issue by afgnsu** [fatfreecrm/fat_free_crm#1298]
My Linux is Manjaro Linux Desktop v 5.15.160-1.

RoR environment is rbenv with ruby 3.2.0 & rails  7.0.8.4.

My database is mysql (MariaDB 11.3.2)

and I setup env with [CI] & [DB] in ~/.bashrc.
--------------------------
CI=true
DB=mysql
--------------------------
I already execute "rails db:create" without any error.

When I input "rake ffcrm:setup" and press 'yes', then got a error message: 

------------------------------------------------------------
Caused by:
NameError: uninitialized constant ConvertToActiveStorage::PG (NameError)

      if conn.is_a?(PG::Connection)
                      ^^^^^^^^^^^^
/home/patrick/projects/fat_free_crm/db/migrate/20230526212613_convert_to_active_storage.rb:19:in `block in up'
/home/patrick/projects/fat_free_crm/db/migrate/20230526212613_convert_to_active_storage.rb:18:in `up'
/home/patrick/projects/fat_free_crm/lib/tasks/ffcrm/setup.rake:22:in `block (2 levels) in <main>'
------------------------------------------------------------

Who can help me?

**Comment by afgnsu** [comment]
![2024-06-29_06-11](https://github.com/fatfreecrm/fat_free_crm/assets/7204469/054ccd51-6a30-4fb5-b5c7-36e434832d28)
