### ISSUE TITLE
Can't add date pair custom field

### ISSUE THREAD

**Issue by steveyken** [fatfreecrm/fat_free_crm#391]
* Goto admin/fields
* Create date pair custom field

Receive error message:

    ActiveRecord::StatementInvalid (PG::DuplicateColumn: ERROR:  column "cf_a_date_pair" of relation "contacts" already exists
    : ALTER TABLE "contacts" ADD COLUMN "cf_a_date_pair" date):
      app/models/fields/custom_field.rb:128:in `add_column'
      app/models/fields/custom_field_pair.rb:19:in `create_pair'
      app/controllers/admin/fields_controller.rb:46:in `create'

**Comment by steveyken** [comment]
Wow... impressed. How on earth did you find that?

**Comment by steveyken** [comment]
works a treat.
