### ISSUE TITLE
Error running rake or rails in rails4 branch

### ISSUE THREAD

**Issue by steveyken** [fatfreecrm/fat_free_crm#411]
I can't seem to do anything now I've updated to the latest rails4 branch. However, TravisCI is working fine so I suspect something wrong with my instance. I've checked I have no local changes, have run ```bundle install``` and

Error when running ```rails server``` or ```rake anything```

```
rake aborted!
NameError: uninitialized constant Ransack::Constants
/home/steve/.rvm/gems/ruby-2.1.5@fat_free_crm/gems/ransack-1.5.1/lib/ransack/helpers/form_builder.rb:6:in `<top (required)>'
/home/steve/.rvm/gems/ruby-2.1.5@fat_free_crm/gems/ransack_ui-1.3.0/lib/ransack_ui/ransack_overrides/helpers/form_builder.rb:1:in `<top (required)>'
/home/steve/.rvm/gems/ruby-2.1.5@fat_free_crm/gems/ransack_ui-1.3.0/lib/ransack_ui.rb:7:in `block in <top (required)>'
/home/steve/.rvm/gems/ruby-2.1.5@fat_free_crm/gems/ransack_ui-1.3.0/lib/ransack_ui.rb:7:in `glob'
/home/steve/.rvm/gems/ruby-2.1.5@fat_free_crm/gems/ransack_ui-1.3.0/lib/ransack_ui.rb:7:in `<top (required)>'
/home/steve/.rvm/gems/ruby-2.1.5@global/gems/bundler-1.7.4/lib/bundler/runtime.rb:76:in `require'
/home/steve/.rvm/gems/ruby-2.1.5@global/gems/bundler-1.7.4/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
/home/steve/.rvm/gems/ruby-2.1.5@global/gems/bundler-1.7.4/lib/bundler/runtime.rb:72:in `each'
/home/steve/.rvm/gems/ruby-2.1.5@global/gems/bundler-1.7.4/lib/bundler/runtime.rb:72:in `block in require'
/home/steve/.rvm/gems/ruby-2.1.5@global/gems/bundler-1.7.4/lib/bundler/runtime.rb:61:in `each'
/home/steve/.rvm/gems/ruby-2.1.5@global/gems/bundler-1.7.4/lib/bundler/runtime.rb:61:in `require'
/home/steve/.rvm/gems/ruby-2.1.5@global/gems/bundler-1.7.4/lib/bundler.rb:133:in `require'
/home/steve/rails/ffcrm/fat_free_crm/config/application.rb:19:in `<top (required)>'
/home/steve/rails/ffcrm/fat_free_crm/Rakefile:5:in `require'
/home/steve/rails/ffcrm/fat_free_crm/Rakefile:5:in `<top (required)>'
/home/steve/.rvm/gems/ruby-2.1.5@fat_free_crm/bin/ruby_executable_hooks:15:in `eval'
/home/steve/.rvm/gems/ruby-2.1.5@fat_free_crm/bin/ruby_executable_hooks:15:in `<main>'
(See full trace by running task with --trace)
```

**Comment by steveyken** [comment]
@warp any thoughts?

**Comment by warp** [comment]
That is the problem I was seeing with ransack 1.6 so I dropped back to 1.5

**Comment by steveyken** [comment]
Odd, this is ransack 1.5.1

**Comment by warp** [comment]
Hmm ok its just similar on ransack 1.6.2 I get uninitialized constant Ransack::Adapters::ActiveRecord::Context::Constants

**Comment by warp** [comment]
I have worked around this issue in https://github.com/fatfreecrm/fat_free_crm/commit/99f4e1f4269054fc85980ce64e04bcf12b3ed66a ideally we would add the require in ransack_ui

**Comment by steveyken** [comment]
Thanks, I've added you as owner to ransack_ui gem :)

**Comment by steveyken** [comment]
did we release a new ransack_ui?

**Comment by warp** [comment]
not yet, I kinda forgot about that one I'll try to do it tonight.

**Comment by steveyken** [comment]
Did you manage to cut a new ransack? I think we should switch to rails4 to
master this week.

**Comment by warp** [comment]
I just push a new ransack_ui and updated the rails4 branch to point to it.
I had completely forgotten about it :)
