### ISSUE TITLE
App breaks on dashboard rendering account(s) managed between user/admin

### ISSUE THREAD

**Issue by ain** [fatfreecrm/fat_free_crm#418]
__Steps to reproduce__:

1. Establish 2 accounts: 
  1. 1 admin account A and 
  2. 1 user account B
2. Log in with user account B
3. Create Account X
4. Log in with admin account 
5. Create a Note on Account X
6. Log in with user account B

__What happens__: following error is thrown, application remains broken, no known recovery possible:

```
Started GET "/" for 127.0.0.1 at 2015-01-29 23:03:54 +0100
Processing by HomeController#index as HTML
  User Load (0.2ms)  SELECT `users`.* FROM `users` WHERE `users`.`id` = 2 LIMIT 1
   (0.1ms)  BEGIN
   (0.2ms)  UPDATE `users` SET `last_request_at` = '2015-01-29 22:03:54', `perishable_token` = '9lx9r3dosZNB0BUWsgJI', `updated_at` = '2015-01-29 22:03:54' WHERE `users`.`id` = 2
   (1.2ms)  COMMIT
  Preference Load (0.2ms)  SELECT `preferences`.* FROM `preferences` WHERE `preferences`.`name` = 'locale' AND `preferences`.`user_id` = 2 LIMIT 1
  Setting Load (0.2ms)  SELECT `settings`.* FROM `settings` WHERE `settings`.`name` = 'locale' LIMIT 1
  Preference Load (0.2ms)  SELECT `preferences`.* FROM `preferences` WHERE `preferences`.`name` = 'activity_asset' AND `preferences`.`user_id` = 2 LIMIT 1
  Preference Load (0.2ms)  SELECT `preferences`.* FROM `preferences` WHERE `preferences`.`name` = 'activity_event' AND `preferences`.`user_id` = 2 LIMIT 1
  Preference Load (0.2ms)  SELECT `preferences`.* FROM `preferences` WHERE `preferences`.`name` = 'activity_user' AND `preferences`.`user_id` = 2 LIMIT 1
  Preference Load (0.2ms)  SELECT `preferences`.* FROM `preferences` WHERE `preferences`.`name` = 'activity_duration' AND `preferences`.`user_id` = 2 LIMIT 1
  Version Load (0.2ms)  SELECT `versions`.* FROM `versions` WHERE (versions.created_at >= '2015-01-27 22:03:54') ORDER BY created_at DESC LIMIT 500
  User Load (0.2ms)  SELECT `users`.* FROM `users` WHERE `users`.`id` IN (2, 1)
  Avatar Load (0.1ms)  SELECT `avatars`.* FROM `avatars` WHERE `avatars`.`entity_type` = 'User' AND `avatars`.`entity_id` IN (2, 1)
  CACHE (0.0ms)  SELECT `users`.* FROM `users` WHERE `users`.`id` IN (2, 1)
  Account Load (0.2ms)  SELECT `accounts`.* FROM `accounts` WHERE `accounts`.`id` IN (3)
  Setting Load (0.3ms)  SELECT `settings`.* FROM `settings` WHERE `settings`.`name` = 'account_category_color' LIMIT 1
  Setting Load (0.1ms)  SELECT `settings`.* FROM `settings` WHERE `settings`.`name` = 'opportunity_stage_color' LIMIT 1
  Setting Load (0.1ms)  SELECT `settings`.* FROM `settings` WHERE `settings`.`name` = 'task_category_color' LIMIT 1
  Rendered shared/_inline_styles.html.haml (2.5ms)
   (0.2ms)  SELECT COUNT(*) FROM `tasks` WHERE ((user_id = 2 AND assigned_to IS NULL) OR assigned_to = 2) AND (completed_at IS NULL)
   (0.2ms)  SELECT COUNT(*) FROM `opportunities` WHERE ((user_id = 2 AND assigned_to IS NULL) OR assigned_to = 2) AND (opportunities.stage != 'won') AND (opportunities.stage != 'lost')
   (0.2ms)  SELECT COUNT(*) FROM `accounts` WHERE ((user_id = 2 AND assigned_to IS NULL) OR assigned_to = 2)
  Account Load (0.8ms)  SELECT `accounts`.* FROM `accounts` WHERE ((user_id = 2 AND assigned_to IS NULL) OR assigned_to = 2) ORDER BY name LIMIT 10
  User Load (0.3ms)  SELECT `users`.* FROM `users` WHERE `users`.`id` IN (2)
  ActsAsTaggableOn::Tagging Load (0.2ms)  SELECT `taggings`.* FROM `taggings` WHERE `taggings`.`taggable_type` = 'Account' AND `taggings`.`taggable_id` IN (3) AND (taggings.context = 'tags')
  Opportunity Load (1.1ms)  SELECT DISTINCT `opportunities`.* FROM `opportunities` INNER JOIN `account_opportunities` ON `opportunities`.`id` = `account_opportunities`.`opportunity_id` WHERE `account_opportunities`.`account_id` = 3 AND (opportunities.stage <> 'lost') ORDER BY opportunities.id DESC
  Preference Load (0.5ms)  SELECT `preferences`.* FROM `preferences` WHERE `preferences`.`name` = 'accounts_index_view' AND `preferences`.`user_id` = 2 LIMIT 1
   (0.2ms)  SELECT DISTINCT COUNT(DISTINCT `contacts`.`id`) FROM `contacts` INNER JOIN `account_contacts` ON `contacts`.`id` = `account_contacts`.`contact_id` WHERE `account_contacts`.`account_id` = 3
   (0.2ms)  SELECT DISTINCT COUNT(DISTINCT `opportunities`.`id`) FROM `opportunities` INNER JOIN `account_opportunities` ON `opportunities`.`id` = `account_opportunities`.`opportunity_id` WHERE `account_opportunities`.`account_id` = 3
  Rendered home/_account.html.haml (16.7ms)
  Rendered home/index.html.haml within layouts/application (39.5ms)
Completed 500 Internal Server Error in 75.1ms

ActionView::Template::Error (undefined method `name' for nil:NilClass):
    23:         = t(:phone_small) << ": " << (account.toll_free_phone || account.phone) << " | " if account.toll_free_phone? || account.phone?
    24:         = t('pluralize.contact', account.contacts.count) << " | "
    25:         = t('pluralize.opportunity', account.opportunities.count)
    26:       - if account.tags.any?
    27:         %dt
    28:           .tags= tags_for_dashboard(account)
    29:       = hook(:account_bottom, self, :account => account)
  app/views/home/_account.html.haml:26:in `_app_views_home__account_html_haml__1689247447112159022_70262891069720'
  app/views/home/index.html.haml:26:in `_app_views_home_index_html_haml___1156484151330759371_70262897725820'
  app/controllers/home_controller.rb:16:in `index'


  Rendered /Users/ain/.rvm/gems/ruby-2.2.0/gems/actionpack-3.2.21/lib/action_dispatch/middleware/templates/rescues/_trace.erb (1.3ms)
  Rendered /Users/ain/.rvm/gems/ruby-2.2.0/gems/actionpack-3.2.21/lib/action_dispatch/middleware/templates/rescues/_request_and_response.erb (0.9ms)
  Rendered /Users/ain/.rvm/gems/ruby-2.2.0/gems/actionpack-3.2.21/lib/action_dispatch/middleware/templates/rescues/template_error.erb within rescues/layout (31.4ms)
/Users/ain/.rvm/gems/ruby-2.2.0/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:430: warning: Comparable#== will no more rescue exceptions of #<=> in the next release.
/Users/ain/.rvm/gems/ruby-2.2.0/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:430: warning: Return nil in #<=> if the comparison is inappropriate or avoid such comparison.

```

__Platform__:
```
Mac OS X 10.10.2 Yosemite
ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-darwin14]
5.6.20 MySQL Community Server (GPL)
```

**Comment by steveyken** [comment]
Hi, thanks for detailed steps. I'm a bit confused by what you mean on step
5 "Create a Not on Account X" - could you explain as I suspect it's one of
the important steps!
Thanks

**Comment by ain** [comment]
What I meant is creating a Note.

-- 
Sent from Gmail Mobile

**Comment by ain** [comment]
Had this again today on another instance installed few days ago. From the log:

```
Processing by HomeController#index as HTML
  Rendered shared/_inline_styles.html.haml (3.5ms)
  Rendered home/_task.html.haml (16.2ms)
  Rendered home/_opportunity.html.haml (6.4ms)
  Rendered home/index.html.haml within layouts/application (40.0ms)
Completed 500 Internal Server Error in 92.2ms

ActionView::Template::Error (undefined method `name' for nil:NilClass):
    35:             %span.warn= t(:past_due, distance_of_time_in_words(opportunity.closes_on, Date.today))
    36:         - else
    37:           = t(:no_closing_date)
    38:       - if opportunity.tags.any?
    39:         %dt
    40:           .tags= tags_for_dashboard(opportunity)
    41:       = hook(:opportunity_bottom, self, :opportunity => opportunity)
  app/views/home/_opportunity.html.haml:38:in `_app_views_home__opportunity_html_haml___2479362078889029443_67954440'
  app/views/home/index.html.haml:17:in `_app_views_home_index_html_haml__2365221590707333868_18179180'
  app/controllers/home_controller.rb:16:in `index'
```

Happened on iPhone.

**Comment by steveyken** [comment]
Just a thought, but it could be in ```app/helpers/tags_helper.rb``` if ```model.tags``` was returning a nil tag. Shouldn't be happening but perhaps something didn't get cleaned up correctly.

**Comment by ain** [comment]
Nice. I'll have a look. The patch I did did not make sense, I agree, but it works, also for _Opportunities_. Will investigate tonight, leave it on me.
