### ISSUE TITLE
rake db:create fails aborted

### ISSUE THREAD

**Issue by thepaperescape** [fatfreecrm/fat_free_crm#501]
I get this after rake db:create:

```
pi@rpi:~/fat_free_crm $ rake db:create
[DEPRECATION] `last_comment` is deprecated.  Please use `last_description` instead.
[DEPRECATION] `last_comment` is deprecated.  Please use `last_description` instead.
[DEPRECATION] `last_comment` is deprecated.  Please use `last_description` instead.
[DEPRECATION] `last_comment` is deprecated.  Please use `last_description` instead.
[DEPRECATION] `last_comment` is deprecated.  Please use `last_description` instead.
[DEPRECATION] `last_comment` is deprecated.  Please use `last_description` instead.
[DEPRECATION] `last_comment` is deprecated.  Please use `last_description` instead.
[DEPRECATION] `last_comment` is deprecated.  Please use `last_description` instead.
[DEPRECATION] `last_comment` is deprecated.  Please use `last_description` instead.
rake aborted!
YAML syntax error occurred while parsing /home/pi/fat_free_crm/config/database.yml. Please note that YAML must be consistently indented using spaces. Tabs are not allowed. Error: (<unknown>): could not find expected ':' while scanning a simple key at line 5 column 3
/var/lib/gems/2.3.0/gems/railties-4.2.6/lib/rails/application/configuration.rb:115:in `rescue in database_configuration'
/var/lib/gems/2.3.0/gems/railties-4.2.6/lib/rails/application/configuration.rb:98:in `database_configuration'
/var/lib/gems/2.3.0/gems/activerecord-4.2.6/lib/active_record/railtie.rb:41:in `block (3 levels) in <class:Railtie>'
/var/lib/gems/2.3.0/gems/rake-11.2.2/exe/rake:27:in `<top (required)>'
Psych::SyntaxError: (<unknown>): could not find expected ':' while scanning a simple key at line 5 column 3
/var/lib/gems/2.3.0/gems/railties-4.2.6/lib/rails/application/configuration.rb:104:in `database_configuration'
/var/lib/gems/2.3.0/gems/activerecord-4.2.6/lib/active_record/railtie.rb:41:in `block (3 levels) in <class:Railtie>'
/var/lib/gems/2.3.0/gems/rake-11.2.2/exe/rake:27:in `<top (required)>'
Tasks: TOP => db:create => db:load_config
(See full trace by running task with --trace)
```

The only thing that was changed in dependency was upgrade of scrypt to 3.0.3 from 2.0.2 so it would compile on ARM and bundle install would complete. However, once this rake failed I also updated rake, rspec, rspec-expectations, rspec-rails, guard-rspec in Gemfile.lock and received the same fail. What is going on? What should I do? Trying to install fat_free_crm on raspberry pi 3. HALP!

**Comment by CloCkWeRX** [comment]
See also #500

**Comment by johnnyshields** [comment]
@thepaperescape can you confirm if the issue persists on latest master? Otherwise we'll close it.
