### ISSUE TITLE
undefined local variable or method `one_submit_only'

### ISSUE THREAD

**Issue by ain** [fatfreecrm/fat_free_crm#552]
__Steps to reproduce__:

1. Follow installation steps as documented in [Add the Fat Free CRM gem to a new Rails application](https://github.com/fatfreecrm/fat_free_crm/wiki/Running-as-a-Rails-Engine#add-the-fat-free-crm-gem-to-a-new-rails-application)
2. Instead of `rails server`, run server with `phusion/passenger-ruby23 ` Docker image
3. Access container locally at `/login`

__What happens__:  error is thrown:

```
Started GET "/login" for 192.168.99.1 at 2017-02-01 00:51:25 +0000
Cannot render console from 192.168.99.1! Allowed networks: 127.0.0.1, ::1, 127.0.0.0/127.255.255.255
Processing by AuthenticationsController#new as HTML
  Rendered /usr/local/rvm/gems/ruby-2.3.3/gems/fat_free_crm-0.15.0.beta/app/views/authentications/new.html.haml within layouts/application (54.9ms)
Completed 500 Internal Server Error in 456ms (ActiveRecord: 2.3ms)

ActionView::Template::Error (undefined local variable or method `one_submit_only' for #<#<Class:0x0000000537b220>:0x0000000536f0d8>):
    1: .standalone#standalone
    2:   -# The following form gets submitted to #create when @authentication is nil,
    3:   -# or to #update when @authentication is not nil (ex. suspended).
    4:   = form_for @authentication, :url => authentication_path, :html => one_submit_only do |f|
    5:     - if can_signup?
    6:       .title_tools #{t :no_account} #{link_to t(:sign_up_now), signup_path}
    7:     .title= t(:login)
  fat_free_crm (0.15.0.beta) app/views/authentications/new.html.haml:4:in `__usr_local_rvm_gems_ruby_______gems_fat_free_crm________beta_app_views_authentications_new_html_haml___243032229336022934_43643120'
  actionview (4.2.7.1) lib/action_view/template.rb:145:in `block in render'
  activesupport (4.2.7.1) lib/active_support/notifications.rb:166:in `instrument'
  actionview (4.2.7.1) lib/action_view/template.rb:333:in `instrument'
  actionview (4.2.7.1) lib/action_view/template.rb:143:in `render'
  actionview (4.2.7.1) lib/action_view/renderer/template_renderer.rb:54:in `block (2 levels) in render_template'
  actionview (4.2.7.1) lib/action_view/renderer/abstract_renderer.rb:39:in `block in instrument'
  activesupport (4.2.7.1) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.7.1) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.7.1) lib/active_support/notifications.rb:164:in `instrument'
  actionview (4.2.7.1) lib/action_view/renderer/abstract_renderer.rb:39:in `instrument'
  actionview (4.2.7.1) lib/action_view/renderer/template_renderer.rb:53:in `block in render_template'
  actionview (4.2.7.1) lib/action_view/renderer/template_renderer.rb:61:in `render_with_layout'
  actionview (4.2.7.1) lib/action_view/renderer/template_renderer.rb:52:in `render_template'
  actionview (4.2.7.1) lib/action_view/renderer/template_renderer.rb:14:in `render'
  actionview (4.2.7.1) lib/action_view/renderer/renderer.rb:46:in `render_template'
  actionview (4.2.7.1) lib/action_view/renderer/renderer.rb:27:in `render'
  actionview (4.2.7.1) lib/action_view/rendering.rb:100:in `_render_template'
  actionpack (4.2.7.1) lib/action_controller/metal/streaming.rb:217:in `_render_template'
  actionview (4.2.7.1) lib/action_view/rendering.rb:83:in `render_to_body'
  actionpack (4.2.7.1) lib/action_controller/metal/rendering.rb:32:in `render_to_body'
  actionpack (4.2.7.1) lib/action_controller/metal/renderers.rb:37:in `render_to_body'
  actionpack (4.2.7.1) lib/abstract_controller/rendering.rb:25:in `render'
  actionpack (4.2.7.1) lib/action_controller/metal/rendering.rb:16:in `render'
  actionpack (4.2.7.1) lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
  activesupport (4.2.7.1) lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
  /usr/local/rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/benchmark.rb:308:in `realtime'
  activesupport (4.2.7.1) lib/active_support/core_ext/benchmark.rb:12:in `ms'
  actionpack (4.2.7.1) lib/action_controller/metal/instrumentation.rb:44:in `block in render'
  actionpack (4.2.7.1) lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
  activerecord (4.2.7.1) lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
  actionpack (4.2.7.1) lib/action_controller/metal/instrumentation.rb:43:in `render'
  actionpack (4.2.7.1) lib/action_controller/metal/implicit_render.rb:10:in `default_render'
  actionpack (4.2.7.1) lib/action_controller/metal/implicit_render.rb:5:in `send_action'
  actionpack (4.2.7.1) lib/abstract_controller/base.rb:198:in `process_action'
  actionpack (4.2.7.1) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (4.2.7.1) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
  activesupport (4.2.7.1) lib/active_support/callbacks.rb:117:in `call'
  activesupport (4.2.7.1) lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
  activesupport (4.2.7.1) lib/active_support/callbacks.rb:505:in `call'
  activesupport (4.2.7.1) lib/active_support/callbacks.rb:92:in `__run_callbacks__'
  activesupport (4.2.7.1) lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
  activesupport (4.2.7.1) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.7.1) lib/abstract_controller/callbacks.rb:19:in `process_action'
  actionpack (4.2.7.1) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (4.2.7.1) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
  activesupport (4.2.7.1) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.7.1) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.7.1) lib/active_support/notifications.rb:164:in `instrument'
  actionpack (4.2.7.1) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  actionpack (4.2.7.1) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  activerecord (4.2.7.1) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (4.2.7.1) lib/abstract_controller/base.rb:137:in `process'
  actionview (4.2.7.1) lib/action_view/rendering.rb:30:in `process'
  actionpack (4.2.7.1) lib/action_controller/metal.rb:196:in `dispatch'
  actionpack (4.2.7.1) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  actionpack (4.2.7.1) lib/action_controller/metal.rb:237:in `block in action'
  actionpack (4.2.7.1) lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
  actionpack (4.2.7.1) lib/action_dispatch/routing/route_set.rb:43:in `serve'
  actionpack (4.2.7.1) lib/action_dispatch/journey/router.rb:43:in `block in serve'
  actionpack (4.2.7.1) lib/action_dispatch/journey/router.rb:30:in `each'
  actionpack (4.2.7.1) lib/action_dispatch/journey/router.rb:30:in `serve'
  actionpack (4.2.7.1) lib/action_dispatch/routing/route_set.rb:817:in `call'
  rack (1.6.5) lib/rack/etag.rb:24:in `call'
  rack (1.6.5) lib/rack/conditionalget.rb:25:in `call'
  rack (1.6.5) lib/rack/head.rb:13:in `call'
  actionpack (4.2.7.1) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  actionpack (4.2.7.1) lib/action_dispatch/middleware/flash.rb:260:in `call'
  rack (1.6.5) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.6.5) lib/rack/session/abstract/id.rb:220:in `call'
  actionpack (4.2.7.1) lib/action_dispatch/middleware/cookies.rb:560:in `call'
  activerecord (4.2.7.1) lib/active_record/query_cache.rb:36:in `call'
  activerecord (4.2.7.1) lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
  activerecord (4.2.7.1) lib/active_record/migration.rb:377:in `call'
  actionpack (4.2.7.1) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.2.7.1) lib/active_support/callbacks.rb:88:in `__run_callbacks__'
  activesupport (4.2.7.1) lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
  activesupport (4.2.7.1) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.7.1) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.2.7.1) lib/action_dispatch/middleware/reloader.rb:73:in `call'
  actionpack (4.2.7.1) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  actionpack (4.2.7.1) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  web-console (2.3.0) lib/web_console/middleware.rb:20:in `block in call'
  web-console (2.3.0) lib/web_console/middleware.rb:18:in `catch'
  web-console (2.3.0) lib/web_console/middleware.rb:18:in `call'
  actionpack (4.2.7.1) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.7.1) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.7.1) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.7.1) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.7.1) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.7.1) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.7.1) lib/rails/rack/logger.rb:20:in `call'
  request_store (1.3.2) lib/request_store/middleware.rb:9:in `call'
  actionpack (4.2.7.1) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.5) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.5) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.7.1) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  rack (1.6.5) lib/rack/lock.rb:17:in `call'
  actionpack (4.2.7.1) lib/action_dispatch/middleware/static.rb:120:in `call'
  rack (1.6.5) lib/rack/sendfile.rb:113:in `call'
  railties (4.2.7.1) lib/rails/engine.rb:518:in `call'
  railties (4.2.7.1) lib/rails/application.rb:165:in `call'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:97:in `process_request'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:152:in `accept_and_process_next_request'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:113:in `main_loop'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:416:in `block (3 levels) in start_threads'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'


  Rendered /usr/local/rvm/gems/ruby-2.3.3/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/templates/rescues/_source.erb (4.4ms)
  Rendered /usr/local/rvm/gems/ruby-2.3.3/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (2.1ms)
  Rendered /usr/local/rvm/gems/ruby-2.3.3/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (1.3ms)
  Rendered /usr/local/rvm/gems/ruby-2.3.3/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/templates/rescues/template_error.html.erb within rescues/layout (33.8ms)
```

__What should happen__: login screen should appear without error.

**Comment by CloCkWeRX** [comment]
Can I get you to check exactly which methods are avail in your ApplicationHelper, the step:

```
(cd app && rm -f controllers/application_controller.rb \
views/layouts/application.html.erb helpers/application_helper.rb \
assets/javascripts/application.js assets/stylesheets/application.css)
```
potentially clobbered
```
app/helpers/application_helper.rb
208:  def one_submit_only(_form = '')
```
alternatively it's not properly including the right ApplicationHelper.

**Comment by ain** [comment]
You were correct, it was the `application_helper.rb` failure. After fixing it, both, `0.14.0` and `0.15.0.beta` work smoothly.

Thanks a lot for prompt support!
