### ISSUE TITLE
Plugin failure despite following latest documentation

### ISSUE THREAD

**Issue by ain** [fatfreecrm/fat_free_crm#561]
__Steps to reproduce__:

1. Clone FFCRM
2. Start new plugin development as by [documentation](https://github.com/fatfreecrm/fat_free_crm/wiki/Creating-a-plugin#adding-model-methods-to-your-plugin) or clone [ain/ffcrm_due_two_weeks](https://github.com/ain/ffcrm_due_two_weeks)
3. Implement plugin model method of `two_weeks` on `Task` returning string `2 weeks`
3. Add new plugin to FFCRM dependencies
4. Install dependencies

        $ bundle

5. Create user account

        $ bundle exec rake ffcrm:setup

6. Create a task
6. Start Rails console

        $ bundle exec rails c

7. Validate if plugin method works

        > Task.first.two_weeks

__What happens__: 

``` > Task.first.two_weeks
  Task Load (0.2ms)  SELECT  `tasks`.* FROM `tasks`  ORDER BY `tasks`.`id` ASC LIMIT 1
NoMethodError: undefined method `two_weeks' for #<Task:0x00000005ed8230>
	from /usr/local/rvm/gems/ruby-2.4.0/bundler/gems/rails-9ff7fe1a2b86/activemodel/lib/active_model/attribute_methods.rb:433:in `method_missing'
	from /usr/local/rvm/gems/ruby-2.4.0/bundler/gems/fat_free_crm-ca59028e5d1c/lib/fat_free_crm/fields.rb:88:in `method_missing'
	from (irb):3
	from /usr/local/rvm/gems/ruby-2.4.0/bundler/gems/rails-9ff7fe1a2b86/railties/lib/rails/commands/console.rb:110:in `start'
	from /usr/local/rvm/gems/ruby-2.4.0/bundler/gems/rails-9ff7fe1a2b86/railties/lib/rails/commands/console.rb:9:in `start'
	from /usr/local/rvm/gems/ruby-2.4.0/bundler/gems/rails-9ff7fe1a2b86/railties/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /usr/local/rvm/gems/ruby-2.4.0/bundler/gems/rails-9ff7fe1a2b86/railties/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /usr/local/rvm/gems/ruby-2.4.0/bundler/gems/rails-9ff7fe1a2b86/railties/lib/rails/commands.rb:17:in `<top (required)>'
	from /usr/local/rvm/gems/ruby-2.4.0/bundler/gems/rails-9ff7fe1a2b86/activesupport/lib/active_support/dependencies.rb:274:in `require'
	from /usr/local/rvm/gems/ruby-2.4.0/bundler/gems/rails-9ff7fe1a2b86/activesupport/lib/active_support/dependencies.rb:274:in `block in require'
	from /usr/local/rvm/gems/ruby-2.4.0/bundler/gems/rails-9ff7fe1a2b86/activesupport/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /usr/local/rvm/gems/ruby-2.4.0/bundler/gems/rails-9ff7fe1a2b86/activesupport/lib/active_support/dependencies.rb:274:in `require'
	from /home/app/bin/rails:9:in `<top (required)>'
	from /usr/local/rvm/gems/ruby-2.4.0/bundler/gems/rails-9ff7fe1a2b86/activesupport/lib/active_support/dependencies.rb:268:in `load'
	from /usr/local/rvm/gems/ruby-2.4.0/bundler/gems/rails-9ff7fe1a2b86/activesupport/lib/active_support/dependencies.rb:268:in `block in load'
	from /usr/local/rvm/gems/ruby-2.4.0/bundler/gems/rails-9ff7fe1a2b86/activesupport/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /usr/local/rvm/gems/ruby-2.4.0/bundler/gems/rails-9ff7fe1a2b86/activesupport/lib/active_support/dependencies.rb:268:in `load'
	from /usr/local/rvm/gems/ruby-2.4.0/gems/spring-2.0.1/lib/spring/commands/rails.rb:6:in `call'
	from /usr/local/rvm/gems/ruby-2.4.0/gems/spring-2.0.1/lib/spring/command_wrapper.rb:38:in `call'
	from /usr/local/rvm/gems/ruby-2.4.0/gems/spring-2.0.1/lib/spring/application.rb:191:in `block in serve'
	from /usr/local/rvm/gems/ruby-2.4.0/gems/spring-2.0.1/lib/spring/application.rb:161:in `fork'
	from /usr/local/rvm/gems/ruby-2.4.0/gems/spring-2.0.1/lib/spring/application.rb:161:in `serve'
	from /usr/local/rvm/gems/ruby-2.4.0/gems/spring-2.0.1/lib/spring/application.rb:131:in `block in run'
	from /usr/local/rvm/gems/ruby-2.4.0/gems/spring-2.0.1/lib/spring/application.rb:125:in `loop'
	from /usr/local/rvm/gems/ruby-2.4.0/gems/spring-2.0.1/lib/spring/application.rb:125:in `run'
	from /usr/local/rvm/gems/ruby-2.4.0/gems/spring-2.0.1/lib/spring/application/boot.rb:19:in `<top (required)>'
	from /usr/local/rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from -e:1:in `<main>'

```

__What should happen__: 

```
> Task.first.two_weeks
=> "2 weeks"
```

**Comment by ain** [comment]
The same code works on `Account`, but not on `Task`. Any tips appreciated.

**Comment by CloCkWeRX** [comment]
I've had similar issues, which I vaguely pinned down to 'rails autoloads things weirdly sometimes'.

One method, which certainly isn't fantastic, is to reopen the class and define methods on it in an intializer or during the rails app configuring itself.

http://stefan.haflidason.com/extending-engine-models-in-rails-4/ talks about it when code is loaded as an engine

Example:

config/application.rb
```
    config.to_prepare do
      Contact.class_eval do
        include ContactIndexer

        has_many :documents, as: :owner

        # Avoid conflicting definitions of search()
        # https://github.com/activerecord-hackery/ransack/blob/master/lib/ransack/adapters/active_record/base.rb
        def self.search(params = {}, options = {})
          ransack(params, options)
        end
        scope :active, -> {
          where(
              "contacts.deleted_at IS NULL OR contacts.deleted_at >= CURRENT_DATE"
          )
        }
      end
    end
```
Certainly not pretty, but for a very limited use case; workable.

**Comment by johnnyshields** [comment]
Closing as this is not an FFCRM specific issue; its related to Rails autoload
