### ISSUE TITLE
Migrations: ActiveRecord::ActiveRecordError: contacts_count is marked as readonly

### ISSUE THREAD

**Issue by CloCkWeRX** [fatfreecrm/fat_free_crm#685]
#651 regression

Migrations on old DB schema can fail:
```
== 20180102075234 AddAccountCounterCaches: migrating ==========================
-- change_table(:accounts)
   -> 1.3639s
rails aborted!
StandardError: An error has occurred, this and all later migrations canceled:

contacts_count is marked as readonly
/Users/dan/htw-all/fat_free_crm/db/migrate/20180102075234_add_account_counter_caches.rb:17:in `block in data'
/Users/dan/htw-all/fat_free_crm/db/migrate/20180102075234_add_account_counter_caches.rb:16:in `data'
/Users/dan/htw-all/fat_free_crm/db/migrate/20180102075234_add_account_counter_caches.rb:11:in `block (2 levels) in change'
/Users/dan/htw-all/fat_free_crm/db/migrate/20180102075234_add_account_counter_caches.rb:11:in `block in change'
/Users/dan/htw-all/fat_free_crm/db/migrate/20180102075234_add_account_counter_caches.rb:10:in `change'
bin/rails:6:in `<main>'

Caused by:
ActiveRecord::ActiveRecordError: contacts_count is marked as readonly
/Users/dan/htw-all/fat_free_crm/db/migrate/20180102075234_add_account_counter_caches.rb:17:in `block in data'
/Users/dan/htw-all/fat_free_crm/db/migrate/20180102075234_add_account_counter_caches.rb:16:in `data'
/Users/dan/htw-all/fat_free_crm/db/migrate/20180102075234_add_account_counter_caches.rb:11:in `block (2 levels) in change'
/Users/dan/htw-all/fat_free_crm/db/migrate/20180102075234_add_account_counter_caches.rb:11:in `block in change'
/Users/dan/htw-all/fat_free_crm/db/migrate/20180102075234_add_account_counter_caches.rb:10:in `change'
bin/rails:6:in `<main>'
```

**Comment by CloCkWeRX** [comment]
Ugh, annoying. Can't use reset counters because the activemodel representation doesn't know it just grew counter_caches.

Might need to move this to a rake task, and make note in the changelog/have this migration emit a "Please run ..." message.

Or whatever http://ryan.mcgeary.org/2016/02/05/proper-counter-cache-migrations-in-rails/ says

**Comment by johnnyshields** [comment]
strange i didn't get that error. Can either run it as a vanilla SQL query or hack the meta-data so that for the scope of the migration it's not readonly

**Comment by johnnyshields** [comment]
@mesmerze can you help with a PR for this?
