### ISSUE TITLE
Passing string to define a callback is not supported.

### ISSUE THREAD

**Issue by legacy370** [fatfreecrm/fat_free_crm#687]
Under Ruby 2.4.1 and Rails 5.1.4, the application failed to come up.  It emitted errors in Passenger, namely "Passing string to define a callback is not supported. See the `.set_callback` documentation to see supported values."  These messages were coming from various programs in app/controllers/admin, specifically in lines 6 or 7, where they specify a before_action.
--

```

App 18303 stdout: 
App 18303 stdout: 
[ E 2018-01-10 01:43:39.3493 16702/T14 age/Cor/App/Implementation.cpp:304 ]: Could not spawn process for application /home/deploy/fat_free_crm/current: An error occurred while starting up the preloader.
  Error ID: 6564be24
  Error details saved to: /tmp/passenger-error-2bg4Fn.html
  Message from application: Passing string to define a callback is not supported. See the `.set_callback` documentation to see supported values. (ArgumentError)
  /home/deploy/fat_free_crm/shared/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/callbacks.rb:282:in `build'
  /home/deploy/fat_free_crm/shared/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/callbacks.rb:676:in `block in set_callback'
  /home/deploy/fat_free_crm/shared/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/callbacks.rb:675:in `map'
  /home/deploy/fat_free_crm/shared/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/callbacks.rb:675:in `set_callback'
  /home/deploy/fat_free_crm/shared/bundle/ruby/2.4.0/gems/actionpack-5.1.4/lib/abstract_controller/callbacks.rb:167:in `block (3 levels) in <module:ClassMethods>'
  /home/deploy/fat_free_crm/shared/bundle/ruby/2.4.0/gems/actionpack-5.1.4/lib/abstract_controller/callbacks.rb:74:in `block in _insert_callbacks'
  /home/deploy/fat_free_crm/shared/bundle/ruby/2.4.0/gems/actionpack-5.1.4/lib/abstract_controller/callbacks.rb:73:in `each'
  /home/deploy/fat_free_crm/shared/bundle/ruby/2.4.0/gems/actionpack-5.1.4/lib/abstract_controller/callbacks.rb:73:in `_insert_callbacks'
  /home/deploy/fat_free_crm/shared/bundle/ruby/2.4.0/gems/actionpack-5.1.4/lib/abstract_controller/callbacks.rb:166:in `block (2 levels) in <module:ClassMethods>'
  /home/deploy/fat_free_crm/releases/20180110013935/app/controllers/admin/plugins_controller.rb:7:in `<class:PluginsController>'
  /home/deploy/fat_free_crm/releases/20180110013935/app/controllers/admin/plugins_controller.rb:6:in `<main>'
  /home/deploy/fat_free_crm/shared/bundle/ruby/2.4.0/gems/bootsnap-1.1.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
  /home/deploy/fat_free_crm/shared/bundle/ruby/2.4.0/gems/bootsnap-1.1.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
  /home/deploy/fat_free_crm/shared/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `block in require'
  /home/deploy/fat_free_crm/shared/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:258:in `load_dependency'
  /home/deploy/fat_free_crm/shared/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `require'
  /home/deploy/fat_free_crm/shared/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:379:in `block in require_or_load'
  /home/deploy/fat_free_crm/shared/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:36:in `block in load_interlock'
  /home/deploy/fat_free_crm/shared/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies/interlock.rb:12:in `block in loading'
  /home/deploy/fat_free_crm/shared/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/concurrency/share_lock.rb:149:in `exclusive'
  /home/deploy/fat_free_crm/shared/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies/interlock.rb:11:in `loading'
  /home/deploy/fat_free_crm/shared/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:36:in `load_interlock'
  /home/deploy/fat_free_crm/shared/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:357:in `require_or_load'
  /home/deploy/fat_free_crm/shared/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:335:in `depend_on'
  /home/deploy/fat_free_crm/shared/bundle/ruby/2.4.0/gems/bootsnap-1.1.7/lib/bootsnap/load_path_cache/core_ext/active_support.rb:59:in `depend_on'
  /home/deploy/fat_free_crm/shared/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:251:in `require_dependency'
  /home/deploy/fat_free_crm/shared/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/engine.rb:476:in `block (2 levels) in eager_load!'
  /home/deploy/fat_free_crm/shared/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/engine.rb:475:in `each'
  /home/deploy/fat_free_crm/shared/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/engine.rb:475:in `block in eager_load!'
  /home/deploy/fat_free_crm/shared/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/engine.rb:473:in `each'
  /home/deploy/fat_free_crm/shared/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/engine.rb:473:in `eager_load!'
  /home/deploy/fat_free_crm/shared/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/engine.rb:354:in `eager_load!'
  /home/deploy/fat_free_crm/shared/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/application/finisher.rb:67:in `each'
  /home/deploy/fat_free_crm/shared/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/application/finisher.rb:67:in `block in <module:Finisher>'
  /home/deploy/fat_free_crm/shared/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/initializable.rb:30:in `instance_exec'
  /home/deploy/fat_free_crm/shared/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/initializable.rb:30:in `run'
  /home/deploy/fat_free_crm/shared/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/initializable.rb:59:in `block in run_initializers'
  /home/deploy/.rbenv/versions/2.4.1/lib/ruby/2.4.0/tsort.rb:228:in `block in tsort_each'
  /home/deploy/.rbenv/versions/2.4.1/lib/ruby/2.4.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
  /home/deploy/.rbenv/versions/2.4.1/lib/ruby/2.4.0/tsort.rb:431:in `each_strongly_connected_component_from'
  /home/deploy/.rbenv/versions/2.4.1/lib/ruby/2.4.0/tsort.rb:349:in `block in each_strongly_connected_component'
  /home/deploy/.rbenv/versions/2.4.1/lib/ruby/2.4.0/tsort.rb:347:in `each'
  /home/deploy/.rbenv/versions/2.4.1/lib/ruby/2.4.0/tsort.rb:347:in `call'
  /home/deploy/.rbenv/versions/2.4.1/lib/ruby/2.4.0/tsort.rb:347:in `each_strongly_connected_component'
  /home/deploy/.rbenv/versions/2.4.1/lib/ruby/2.4.0/tsort.rb:226:in `tsort_each'
  /home/deploy/.rbenv/versions/2.4.1/lib/ruby/2.4.0/tsort.rb:205:in `tsort_each'
  /home/deploy/fat_free_crm/shared/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/initializable.rb:58:in `run_initializers'
  /home/deploy/fat_free_crm/shared/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/application.rb:353:in `initialize!'
  /home/deploy/fat_free_crm/shared/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/railtie.rb:185:in `public_send'
  /home/deploy/fat_free_crm/shared/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/railtie.rb:185:in `method_missing'
  /home/deploy/fat_free_crm/releases/20180110013935/config/environment.rb:10:in `<top (required)>'
  config.ru:3:in `require'
  config.ru:3:in `block in <main>'
  /home/deploy/fat_free_crm/shared/bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/builder.rb:55:in `instance_eval'
  /home/deploy/fat_free_crm/shared/bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/builder.rb:55:in `initialize'
  config.ru:1:in `new'
  config.ru:1:in `<main>'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:110:in `eval'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:110:in `preload_app'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:156:in `<module:App>'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:30:in `<module:PhusionPassenger>'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:29:in `<main>'

```

**Comment by johnnyshields** [comment]
@legacy370 can you give the full stack trace?

**Comment by legacy370** [comment]
This is a snippet from /var/log/nginx/error.log
[nginx_snippet.txt](https://github.com/fatfreecrm/fat_free_crm/files/1619505/nginx_snippet.txt)

**Comment by johnnyshields** [comment]
Does it run for you with Puma or a server other than Passenger?
