### ISSUE TITLE
Time or date based regression: I want to manage leads

### ISSUE THREAD

**Issue by CloCkWeRX** [fatfreecrm/fat_free_crm#726]
This started failing everywhere, even on known good commits.

```
  1) Leads 
  In order to increase sales
  As a user
  I want to manage leads
 should create a new lead
     Failure/Error: expect(leads_element).to have_content('Mr Lead')
       expected to find text "Mr Lead" in ""
     # ./spec/features/leads_spec.rb:47:in `block (3 levels) in <main>'
     # ./spec/features/leads_spec.rb:30:in `block (2 levels) in <main>'
```

Passing: https://github.com/fatfreecrm/fat_free_crm/pull/720
Failing: https://github.com/fatfreecrm/fat_free_crm/pull/724

The only thing that has changed is the date/time as far as I know.

**Comment by CloCkWeRX** [comment]
Works if I throw a binding.pry in there and the ajax request(s) are given time to finish.
