### ISSUE TITLE
Failing tests: sqlite

### ISSUE THREAD

**Issue by CloCkWeRX** [fatfreecrm/fat_free_crm#833]
From https://travis-ci.org/fatfreecrm/fat_free_crm/jobs/605790930
```
An error occurred while loading ./spec/models/entities/account_opportunity_spec.rb.

...

ActiveRecord::NotNullViolation:
  SQLite3::ConstraintException: NOT NULL constraint failed: settings.id: INSERT INTO "settings" ("name", "value", "created_at", "updated_at") VALUES (?, ?, ?, ?)
# ./vendor/bundle/ruby/2.4.0/gems/sqlite3-1.3.13/lib/sqlite3/statement.rb:108:in `step'
# ./vendor/bundle/ruby/2.4.0/gems/sqlite3-1.3.13/lib/sqlite3/statement.rb:108:in `block in each'
# ./vendor/bundle/ruby/2.4.0/gems/sqlite3-1.3.13/lib/sqlite3/statement.rb:107:in `loop'
# ./vendor/bundle/ruby/2.4.0/gems/sqlite3-1.3.13/lib/sqlite3/statement.rb:107:in `each'
```

**Comment by CloCkWeRX** [comment]
Annoying:
```
if FatFreeCRM.application?
  require 'fat_free_crm/secret_token_generator'
  FatFreeCRM::SecretTokenGenerator.setup!
end
```

```
      def setup!
        unless token_exists?
          Rails.logger.info("No secret key defined yet... generating and saving to Setting.secret_token")
          new_token!
        end
        # If db isn't setup yet, token will return nil, provide a randomly generated one for now.
        FatFreeCRM::Application.config.secret_key_base = (token || generate_token)
      end
```

```
      #
      # Create a new secret token and save it as a setting.
      def new_token!
        quietly do
          Setting.secret_token = generate_token
        end
      end
```

**Comment by CloCkWeRX** [comment]
Seems working now
