### ISSUE TITLE
Upgrade to rails 6/6.1

### ISSUE THREAD

**Issue by CloCkWeRX** [fatfreecrm/fat_free_crm#842]
https://edgeguides.rubyonrails.org/6_0_release_notes.html#upgrading-to-rails-6-0

Blockers:
 * https://github.com/zendesk/responds_to_parent/pull/6

**Comment by brianpetro** [comment]
Are there any known issues preventing this upgrade?

ActionMailbox(Rails v6) should enable a lot of useful features to be developed. I'm not very familiar with the current email integrations, though, I imagine simply forwarding relevant emails to an action mailbox controller could trigger a variety of useful functions in the CRM.

**Comment by CloCkWeRX** [comment]
Not that I know of, PR's welcome

**Comment by sergeyradov** [comment]
I can take this! Can you please create a branch rails6 for that task?

**Comment by gmhawash** [comment]
> I can take this! Can you please create a branch rails6 for that task?

@sergeyradov have you started on Rails6 upgrade?  I might be able to help

**Comment by krthi** [comment]
@sergeyradov Any update on this?

**Comment by sergeyradov** [comment]
@krthi I haven't worked over this yet.

**Comment by CloCkWeRX** [comment]
@johnbumgardner I think I managed to coax this to upgrade to rails 6; and well, the application starts! Pushed to https://github.com/fatfreecrm/fat_free_crm/tree/rails6

Did you want to have a go at the deprecation warnings and the failing specs? (or #922)

```

Failures:

  1) /home/index should render list of activities if it's not empty
     Failure/Error: expect(view).to render_template(partial: "_activity")

       expecting partial <_activity> but action rendered <[]>.
       Expected {} to include "_activity".
     # ./spec/views/home/index.haml_spec.rb:23:in `block (2 levels) in <main>'

  2) /home/index should render a message if there're no activities
     Failure/Error: expect(rendered).to include("No activity records found.")

       expected "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<rss version=\"2.0\">\n  <channel>\n    <generator>Fat F...te>Sun, 09 May 2021 00:54:44 +0930</pubDate>\n    <title>Activities</title>\n  </channel>\n</rss>\n" to include "No activity records found."
       Diff:
       @@ -1,9 +1,17 @@
       -No activity records found.
       +<?xml version="1.0" encoding="UTF-8"?>
       +<rss version="2.0">
       +  <channel>
       +    <generator>Fat Free CRM v0.19.1</generator>
       +    <link>http://test.host/</link>
       +    <pubDate>Sun, 09 May 2021 00:54:44 +0930</pubDate>
       +    <title>Activities</title>
       +  </channel>
       +</rss>

     # ./spec/views/home/index.haml_spec.rb:34:in `block (2 levels) in <main>'

Top 10 slowest examples (60.62 seconds, 32.6% of total time):
  Accounts
  In order to increase customer satisfaction
  As a user
  I want to manage accounts
 should create a new account
    8.69 seconds ./spec/features/accounts_spec.rb:27
  Leads
  In order to increase sales
  As a user
  I want to manage leads
 should create a new lead
    7.45 seconds ./spec/features/leads_spec.rb:29
  Opportunities
  In order to increase sales
  As a user
  I want to manage opportunities
 should create a new opportunity
    7.05 seconds ./spec/features/opportunities_spec.rb:28
  Leads
  In order to increase sales
  As a user
  I want to manage leads
 should view and edit a lead
    6.81 seconds ./spec/features/leads_spec.rb:75
  Contacts
  In order to increase customer satisfaction
  As a user
  I want to manage contacts
 should view and edit a contact
    5.71 seconds ./spec/features/contacts_spec.rb:67
  Leads
  In order to increase sales
  As a user
  I want to manage leads
 should delete a lead
    5.65 seconds ./spec/features/leads_spec.rb:95
  Tasks
  In order to increase keep track of things
  As a user
  I want to manage tasks
 creating a task for another user
    5.5 seconds ./spec/features/tasks_spec.rb:47
  Tasks
  In order to increase keep track of things
  As a user
  I want to manage tasks
 should create a new task
    4.85 seconds ./spec/features/tasks_spec.rb:29
  Opportunities
  In order to increase sales
  As a user
  I want to manage opportunities
 should view and edit an opportunity
    4.61 seconds ./spec/features/opportunities_spec.rb:79
  Campaigns
  In order to increase customer satisfaction
  As a user
  I want to manage campaigns
 should create a campaign
    4.3 seconds ./spec/features/campaigns_spec.rb:28

Top 10 slowest example groups:
  Leads
  In order to increase sales
  As a user
  I want to manage leads
    4.03 seconds average (24.18 seconds / 6 examples) ./spec/features/leads_spec.rb:10
  Accounts
  In order to increase customer satisfaction
  As a user
  I want to manage accounts
    3.2 seconds average (22.37 seconds / 7 examples) ./spec/features/accounts_spec.rb:10
  Users tab
  In order to increase customer satisfaction
  As an administrator
  I want to manage users
    3.17 seconds average (3.17 seconds / 1 example) ./spec/features/admin/users_spec.rb:10
  Groups tab
  In order to increase customer satisfaction
  As an administrator
  I want to manage groups
    2.88 seconds average (2.88 seconds / 1 example) ./spec/features/admin/groups_spec.rb:10
  Contacts
  In order to increase customer satisfaction
  As a user
  I want to manage contacts
    2.73 seconds average (16.38 seconds / 6 examples) ./spec/features/contacts_spec.rb:10
  Opportunities
  In order to increase sales
  As a user
  I want to manage opportunities
    2.71 seconds average (21.7 seconds / 8 examples) ./spec/features/opportunities_spec.rb:10
  Tasks
  In order to increase keep track of things
  As a user
  I want to manage tasks
    2.51 seconds average (12.56 seconds / 5 examples) ./spec/features/tasks_spec.rb:10
  Campaigns
  In order to increase customer satisfaction
  As a user
  I want to manage campaigns
    2.28 seconds average (13.66 seconds / 6 examples) ./spec/features/campaigns_spec.rb:10
  Dashboard
  In order to monitor activity
  As a user
  I want to see a dashboard
    0.52404 seconds average (1.05 seconds / 2 examples) ./spec/features/dashboard_spec.rb:10
  Opportunities Overview
  In order to keep track of my team's responsibilities
  As a user
  I want to see an overview of opportunities broken down by user
    0.21206 seconds average (0.84826 seconds / 4 examples) ./spec/features/opportunities_overview_spec.rb:10

Finished in 3 minutes 6.1 seconds (files took 2.23 seconds to load)
1702 examples, 2 failures

Failed examples:

rspec ./spec/views/home/index.haml_spec.rb:17 # /home/index should render list of activities if it's not empty
rspec ./spec/views/home/index.haml_spec.rb:26 # /home/index should render a message if there're no activities
```
