### ISSUE TITLE
FatFreeCRM on Heroku

### ISSUE THREAD

**Issue by BerkhanBerkdemir** [fatfreecrm/fat_free_crm#940]
Hi fatfreecrm users!

Recently I wanted to try FFC on Heroku in a `heroku-20` stack. Sadly, I could not make it work. I made some patches in the source-code, but this time I stuck in asset compile stage and Heroku had to `SIGTERM` the build process. Then I ran in Vagrant, but I also had no luck to run due to FFC was looking PostgreSQL socket (I already set `DATABSE_URL` and `config/database.yml` by hand to make sure FFC uses `localhost`). I would like to provide logs and technical details: [fatfreecrm-on-heroku-20.log](https://github.com/fatfreecrm/fat_free_crm/files/6493174/fatfreecrm-on-heroku-20.log). I only followed steps in the Wiki to get the following result in the log file. Then, I started to patch the source-code; however, I found it is useless because I stuck in asset compile.

**Comment by johnbumgardner** [comment]
Hi Berkhan, 

The link to your log doesn't seem to be working.

**Comment by BerkhanBerkdemir** [comment]
> Hi Berkhan,
> 
> The link to your log doesn't seem to be working.

Interesting. I just tried and it was working. Anyway, I am adding it in here as text.

```
-----> Building on the Heroku-20 stack
-----> Determining which buildpack to use for this app
-----> Ruby app detected
-----> Installing bundler 2.2.16
-----> Removing BUNDLED WITH version in the Gemfile.lock
-----> Compiling Ruby/Rails
-----> Using Ruby version: ruby-2.6.6
-----> Installing dependencies using bundler 2.2.16
       Running: BUNDLE_WITHOUT='development:test' BUNDLE_PATH=vendor/bundle BUNDLE_BIN=vendor/bundle/bin BUNDLE_DEPLOYMENT=1 bundle install -j4
       Fetching gem metadata from https://rubygems.org/..........
       Fetching https://github.com/CloCkWeRX/responds_to_parent.git
       Fetching rake 13.0.3
       Installing rake 13.0.3
       Fetching concurrent-ruby 1.1.8
       Fetching minitest 5.14.4
       Fetching zeitwerk 2.4.2
       Fetching thread_safe 0.3.6
       Installing minitest 5.14.4
       Installing zeitwerk 2.4.2
       Installing concurrent-ruby 1.1.8
       Installing thread_safe 0.3.6
       Fetching builder 3.2.4
       Installing builder 3.2.4
       Fetching erubi 1.10.0
       Fetching mini_portile2 2.5.1
       Installing erubi 1.10.0
       Installing mini_portile2 2.5.1
       Fetching racc 1.5.2
       Fetching crass 1.0.6
       Installing crass 1.0.6
       Fetching rack 2.2.3
       Fetching nio4r 2.5.7
       Installing rack 2.2.3
       Installing nio4r 2.5.7 with native extensions
       Installing racc 1.5.2 with native extensions
       Fetching websocket-extensions 0.1.5
       Installing websocket-extensions 0.1.5
       Fetching marcel 1.0.1
       Installing marcel 1.0.1
       Fetching mini_mime 1.1.0
       Fetching acts_as_commentable 4.0.2
       Installing mini_mime 1.1.0
       Installing acts_as_commentable 4.0.2
       Fetching public_suffix 4.0.6
       Installing public_suffix 4.0.6
       Fetching execjs 2.8.0
       Installing execjs 2.8.0
       Fetching bcrypt 3.1.16
       Fetching msgpack 1.4.2
       Installing bcrypt 3.1.16 with native extensions
       Installing msgpack 1.4.2 with native extensions
       Fetching popper_js 2.9.2
       Installing popper_js 2.9.2
       Fetching method_source 1.0.0
       Installing method_source 1.0.0
       Fetching thor 1.1.0
       Installing thor 1.1.0
       Fetching ffi 1.15.0
       Installing ffi 1.15.0 with native extensions

       Fetching tilt 2.0.10
 Installing tilt 2.0.10
       Using bundler 2.2.16
       Fetching cancancan 3.0.2
       Installing cancancan 3.0.2
       Fetching chronic 0.10.2
       Installing chronic 0.10.2
       Fetching climate_control 0.2.0
       Installing climate_control 0.2.0
       Fetching coffee-script-source 1.12.2
       Installing coffee-script-source 1.12.2
       Fetching i18n_data 0.11.0
       Installing i18n_data 0.11.0
       Fetching sixarm_ruby_unaccent 1.2.0
       Installing sixarm_ruby_unaccent 1.2.0
       Fetching unicode_utils 1.4.0
       Installing unicode_utils 1.4.0
       Fetching orm_adapter 0.5.0
       Installing orm_adapter 0.5.0
       Fetching dynamic_form 1.1.4
       Installing dynamic_form 1.1.4
       Fetching email_reply_parser_ffcrm 0.5.0
       Installing email_reply_parser_ffcrm 0.5.0
       Fetching ffaker 2.18.0
       Installing ffaker 2.18.0
       Fetching temple 0.8.2
       Installing temple 0.8.2
       Fetching htmlentities 4.3.4
       Installing htmlentities 4.3.4
       Fetching jquery-migrate-rails 1.2.1
       Fetching libv8-node 15.14.0.1 (x86_64-linux-musl)
       Installing jquery-migrate-rails 1.2.1
       Fetching mime-types-data 3.2021.0225
       Installing mime-types-data 3.2021.0225
       Fetching pg 1.2.3
       Installing pg 1.2.3 with native extensions
       Installing libv8-node 15.14.0.1 (x86_64-linux-musl)
       Fetching rails_serve_static_assets 0.0.5
       Installing rails_serve_static_assets 0.0.5
       Fetching rails_stdout_logging 0.0.5
       Installing rails_stdout_logging 0.0.5
       Fetching rb-fsevent 0.11.0
       Installing rb-fsevent 0.11.0
       Fetching select2-rails 4.0.13
       Installing select2-rails 4.0.13
       Fetching will_paginate 3.3.0
       Installing will_paginate 3.3.0
       Fetching tzinfo 1.2.9
       Installing tzinfo 1.2.9
       Fetching i18n 1.8.10
       Installing i18n 1.8.10
       Fetching websocket-driver 0.7.3
       Installing websocket-driver 0.7.3 with native extensions
       Fetching rack-test 1.1.0
       Installing rack-test 1.1.0
       Fetching sprockets 3.7.2
       Installing sprockets 3.7.2
       Fetching warden 1.2.9
       Installing warden 1.2.9
       Fetching request_store 1.5.0
       Installing request_store 1.5.0
       Fetching mail 2.7.1
       Installing mail 2.7.1
       Fetching autoprefixer-rails 10.2.4.0
       Installing autoprefixer-rails 10.2.4.0
       Fetching uglifier 4.2.0
       Installing uglifier 4.2.0
       Fetching addressable 2.7.0
       Installing addressable 2.7.0
       Fetching puma 5.3.0
       Installing puma 5.3.0 with native extensions
       Fetching nokogiri 1.11.3 (x86_64-linux)
       Installing nokogiri 1.11.3 (x86_64-linux)
       Fetching ransack_chronic 1.1.0
       Installing ransack_chronic 1.1.0
       Fetching terrapin 0.6.0
       Installing terrapin 0.6.0
       Fetching coffee-script 2.4.1
       Installing coffee-script 2.4.1
       Fetching countries 3.1.0
       Installing countries 3.1.0
       Fetching sort_alphabetical 1.1.0
       Installing sort_alphabetical 1.1.0
       Fetching haml 5.2.1
       Installing haml 5.2.1
       Fetching mime-types 3.3.1
       Installing mime-types 3.3.1
       Fetching mini_racer 0.4.0
       Installing mini_racer 0.4.0 with native extensions
       Fetching rails_12factor 0.0.3
       Installing rails_12factor 0.0.3
       Fetching activesupport 6.0.3.7
       Installing activesupport 6.0.3.7
       Fetching bootsnap 1.7.5
       Fetching css_parser 1.9.0
       Installing bootsnap 1.7.5 with native extensions
       Installing css_parser 1.9.0
       Fetching sassc 2.4.0
       Installing sassc 2.4.0 with native extensions
       Fetching rb-inotify 0.10.1
       Installing rb-inotify 0.10.1
       Fetching loofah 2.9.1
       Installing loofah 2.9.1
       Fetching mimemagic 0.3.10
       Installing mimemagic 0.3.10 with native extensions
       Fetching country_select 5.0.1
       Installing country_select 5.0.1
       Fetching rails-dom-testing 2.0.3
       Installing rails-dom-testing 2.0.3
       Fetching globalid 0.4.2
       Installing globalid 0.4.2
       Fetching activemodel 6.0.3.7
       Installing activemodel 6.0.3.7
       Fetching premailer 1.14.3
       Installing premailer 1.14.3
       Fetching sass-listen 4.0.0
       Installing sass-listen 4.0.0
       Fetching rails-html-sanitizer 1.3.0
       Installing rails-html-sanitizer 1.3.0
       Fetching activejob 6.0.3.7
       Installing activejob 6.0.3.7
       Fetching activerecord 6.0.3.7
       Installing activerecord 6.0.3.7
       Fetching activemodel-serializers-xml 1.0.2
       Installing activemodel-serializers-xml 1.0.2
       Fetching rails-observers 0.1.5
       Installing rails-observers 0.1.5
       Fetching sass 3.7.4
       Installing sass 3.7.4
       Fetching actionview 6.0.3.7
       Installing actionview 6.0.3.7
       Fetching acts-as-taggable-on 7.0.0
       Installing acts-as-taggable-on 7.0.0
       Fetching acts_as_list 1.0.4
       Installing acts_as_list 1.0.4
       Fetching paper_trail 12.0.0
       Installing paper_trail 12.0.0
       Fetching ransack 2.4.2
       Installing ransack 2.4.2
       Fetching actionpack 6.0.3.7
       Installing actionpack 6.0.3.7
       Fetching ransack_ui 1.4.0
       Installing ransack_ui 1.4.0
       Fetching actioncable 6.0.3.7
       Installing actioncable 6.0.3.7
       Fetching activestorage 6.0.3.7
       Installing activestorage 6.0.3.7
       Fetching actionmailer 6.0.3.7
       Installing actionmailer 6.0.3.7
       Fetching railties 6.0.3.7
       Installing railties 6.0.3.7
       Fetching sprockets-rails 3.2.2
       Installing sprockets-rails 3.2.2
       Using responds_to_parent 2.0.0 from https://github.com/CloCkWeRX/responds_to_parent.git (at patch-1@fc42ea1)
       Fetching simple_form 5.1.0
       Installing simple_form 5.1.0
       Fetching actionmailbox 6.0.3.7
       Installing actionmailbox 6.0.3.7
       Fetching actiontext 6.0.3.7
       Installing actiontext 6.0.3.7
       Fetching coffee-rails 5.0.0
       Installing coffee-rails 5.0.0
       Fetching responders 3.0.1
       Installing responders 3.0.1
       Fetching font-awesome-rails 4.7.0.7
       Installing font-awesome-rails 4.7.0.7
       Fetching jquery-rails 4.4.0
       Installing jquery-rails 4.4.0
       Fetching jquery-ui-rails 6.0.1
       Installing jquery-ui-rails 6.0.1
       Fetching rails-i18n 6.0.0
       Installing rails-i18n 6.0.0
       Fetching sass-rails 5.0.8
       Installing sass-rails 5.0.8
       Fetching rails 6.0.3.7
       Installing rails 6.0.3.7
       Fetching devise 4.8.0
       Installing devise 4.8.0
       Fetching rails3-jquery-autocomplete 1.0.15
       Installing rails3-jquery-autocomplete 1.0.15
       Fetching rails_autolink 1.1.6
       Installing rails_autolink 1.1.6
       Fetching devise-encryptable 0.2.0
       Installing devise-encryptable 0.2.0
       Fetching devise-i18n 1.9.4
       Installing devise-i18n 1.9.4
       Fetching sassc-rails 2.1.2
       Installing sassc-rails 2.1.2
       Fetching bootstrap 5.0.0
       Installing bootstrap 5.0.0
       Fetching paperclip 6.1.0
       Installing paperclip 6.1.0
       Bundle complete! 76 Gemfile dependencies, 121 gems now installed.
       Gems in the groups 'development' and 'test' were not installed.
       Bundled gems are installed into `./vendor/bundle`
       Post-install message from acts-as-taggable-on:
       When upgrading
       
       Re-run the migrations generator
       
           rake acts_as_taggable_on_engine:install:migrations
       
       This will create any new migrations and skip existing ones
       Version 3.5.0 has a migration for mysql adapter
       Post-install message from paperclip:
       ##################################################
       #  NOTE FOR UPGRADING FROM 4.3.0 OR EARLIER      #
       ##################################################
       
       Paperclip is now compatible with aws-sdk-s3.
       
       If you are using S3 storage, aws-sdk-s3 requires you to make a few small
       changes:
       
       * You must set the `s3_region`
       * If you are explicitly setting permissions anywhere, such as in an initializer,
         note that the format of the permissions changed from using an underscore to
         using a hyphen. For example, `:public_read` needs to be changed to
         `public-read`.
       
       For a walkthrough of upgrading from 4 to *5* (not 6) and aws-sdk >= 2.0 you can watch
       http://rubythursday.com/episodes/ruby-snack-27-upgrade-paperclip-and-aws-sdk-in-prep-for-rails-5
       Post-install message from sass:
       
       Ruby Sass has reached end-of-life and should no longer be used.
       
       * If you use Sass as a command-line tool, we recommend using Dart Sass, the new
         primary implementation: https://sass-lang.com/install
       
       * If you use Sass as a plug-in for a Ruby web framework, we recommend using the
         sassc gem: https://github.com/sass/sassc-ruby#readme
       
       * For more details, please refer to the Sass blog:
         https://sass-lang.com/blog/posts/7828841
       
       Bundle completed (281.72s)
       Cleaning up the bundler cache.
-----> Installing node-v12.16.2-linux-x64
-----> Detecting rake tasks
 !
 !     Could not detect rake tasks
 !     ensure you can run `$ bundle exec rake -P` against your app
 !     and using the production group of your Gemfile.
 !     /tmp/build_4babe5d0/vendor/bundle/ruby/2.6.0/gems/bundler-2.2.16/lib/bundler/spec_set.rb:89:in `block in materialize': Could not find libv8-node-15.14.0.1 in any of the sources (Bundler::GemNotFound)
 !     from /tmp/build_4babe5d0/vendor/bundle/ruby/2.6.0/gems/bundler-2.2.16/lib/bundler/spec_set.rb:82:in `map!'
 !     from /tmp/build_4babe5d0/vendor/bundle/ruby/2.6.0/gems/bundler-2.2.16/lib/bundler/spec_set.rb:82:in `materialize'
 !     from /tmp/build_4babe5d0/vendor/bundle/ruby/2.6.0/gems/bundler-2.2.16/lib/bundler/definition.rb:185:in `specs'
 !     from /tmp/build_4babe5d0/vendor/bundle/ruby/2.6.0/gems/bundler-2.2.16/lib/bundler/definition.rb:255:in `specs_for'
 !     from /tmp/build_4babe5d0/vendor/bundle/ruby/2.6.0/gems/bundler-2.2.16/lib/bundler/definition.rb:237:in `requested_specs'
 !     from /tmp/build_4babe5d0/vendor/bundle/ruby/2.6.0/gems/bundler-2.2.16/lib/bundler/runtime.rb:91:in `block in definition_method'
 !     from /tmp/build_4babe5d0/vendor/bundle/ruby/2.6.0/gems/bundler-2.2.16/lib/bundler/runtime.rb:20:in `setup'
 !     from /tmp/build_4babe5d0/vendor/bundle/ruby/2.6.0/gems/bundler-2.2.16/lib/bundler.rb:148:in `setup'
 !     from /tmp/build_4babe5d0/vendor/bundle/ruby/2.6.0/gems/bundler-2.2.16/lib/bundler/setup.rb:20:in `block in <top (required)>'
 !     from /tmp/build_4babe5d0/vendor/bundle/ruby/2.6.0/gems/bundler-2.2.16/lib/bundler/ui/shell.rb:136:in `with_level'
 !     from /tmp/build_4babe5d0/vendor/bundle/ruby/2.6.0/gems/bundler-2.2.16/lib/bundler/ui/shell.rb:88:in `silence'
 !     from /tmp/build_4babe5d0/vendor/bundle/ruby/2.6.0/gems/bundler-2.2.16/lib/bundler/setup.rb:20:in `<top (required)>'
 !     from /tmp/build_4babe5d0/vendor/ruby-2.6.6/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
 !     from /tmp/build_4babe5d0/vendor/ruby-2.6.6/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
 !     from /tmp/build_4babe5d0/config/boot.rb:12:in `<top (required)>'
 !     from /tmp/build_4babe5d0/bin/rake:4:in `require_relative'
 !     from /tmp/build_4babe5d0/bin/rake:4:in `<main>'
 !
/tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/helpers/rake_runner.rb:106:in `load_rake_tasks!': Could not detect rake tasks (LanguagePack::Helpers::RakeRunner::CannotLoadRakefileError)
ensure you can run `$ bundle exec rake -P` against your app
and using the production group of your Gemfile.
/tmp/build_4babe5d0/vendor/bundle/ruby/2.6.0/gems/bundler-2.2.16/lib/bundler/spec_set.rb:89:in `block in materialize': Could not find libv8-node-15.14.0.1 in any of the sources (Bundler::GemNotFound)
	from /tmp/build_4babe5d0/vendor/bundle/ruby/2.6.0/gems/bundler-2.2.16/lib/bundler/spec_set.rb:82:in `map!'
	from /tmp/build_4babe5d0/vendor/bundle/ruby/2.6.0/gems/bundler-2.2.16/lib/bundler/spec_set.rb:82:in `materialize'
	from /tmp/build_4babe5d0/vendor/bundle/ruby/2.6.0/gems/bundler-2.2.16/lib/bundler/definition.rb:185:in `specs'
	from /tmp/build_4babe5d0/vendor/bundle/ruby/2.6.0/gems/bundler-2.2.16/lib/bundler/definition.rb:255:in `specs_for'
	from /tmp/build_4babe5d0/vendor/bundle/ruby/2.6.0/gems/bundler-2.2.16/lib/bundler/definition.rb:237:in `requested_specs'
	from /tmp/build_4babe5d0/vendor/bundle/ruby/2.6.0/gems/bundler-2.2.16/lib/bundler/runtime.rb:91:in `block in definition_method'
	from /tmp/build_4babe5d0/vendor/bundle/ruby/2.6.0/gems/bundler-2.2.16/lib/bundler/runtime.rb:20:in `setup'
	from /tmp/build_4babe5d0/vendor/bundle/ruby/2.6.0/gems/bundler-2.2.16/lib/bundler.rb:148:in `setup'
	from /tmp/build_4babe5d0/vendor/bundle/ruby/2.6.0/gems/bundler-2.2.16/lib/bundler/setup.rb:20:in `block in <top (required)>'
	from /tmp/build_4babe5d0/vendor/bundle/ruby/2.6.0/gems/bundler-2.2.16/lib/bundler/ui/shell.rb:136:in `with_level'
	from /tmp/build_4babe5d0/vendor/bundle/ruby/2.6.0/gems/bundler-2.2.16/lib/bundler/ui/shell.rb:88:in `silence'
	from /tmp/build_4babe5d0/vendor/bundle/ruby/2.6.0/gems/bundler-2.2.16/lib/bundler/setup.rb:20:in `<top (required)>'
	from /tmp/build_4babe5d0/vendor/ruby-2.6.6/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /tmp/build_4babe5d0/vendor/ruby-2.6.6/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /tmp/build_4babe5d0/config/boot.rb:12:in `<top (required)>'
	from /tmp/build_4babe5d0/bin/rake:4:in `require_relative'
	from /tmp/build_4babe5d0/bin/rake:4:in `<main>'
	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/ruby.rb:1030:in `rake'
	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/rails4.rb:78:in `block (2 levels) in run_assets_precompile_rake_task'
	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/base.rb:190:in `log'
	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/rails4.rb:72:in `block in run_assets_precompile_rake_task'
	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/instrument.rb:18:in `block (2 levels) in instrument'
	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/instrument.rb:40:in `yield_with_block_depth'
	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/instrument.rb:17:in `block in instrument'
	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/vendor/ruby/heroku-20/lib/ruby/2.6.0/benchmark.rb:308:in `realtime'
	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/instrument.rb:16:in `instrument'
	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/base.rb:50:in `instrument'
	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/base.rb:46:in `instrument'
	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/rails4.rb:71:in `run_assets_precompile_rake_task'
	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/ruby.rb:112:in `block (2 levels) in compile'
	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/ruby.rb:1051:in `allow_git'
	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/ruby.rb:105:in `block in compile'
	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/instrument.rb:18:in `block (2 levels) in instrument'
	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/instrument.rb:40:in `yield_with_block_depth'
	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/instrument.rb:17:in `block in instrument'
	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/vendor/ruby/heroku-20/lib/ruby/2.6.0/benchmark.rb:308:in `realtime'
	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/instrument.rb:16:in `instrument'
	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/base.rb:50:in `instrument'
	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/base.rb:46:in `instrument'
	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/ruby.rb:91:in `compile'
	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/rails2.rb:62:in `block in compile'
	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/instrument.rb:18:in `block (2 levels) in instrument'
	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/instrument.rb:40:in `yield_with_block_depth'
	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/instrument.rb:17:in `block in instrument'
	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/vendor/ruby/heroku-20/lib/ruby/2.6.0/benchmark.rb:308:in `realtime'
	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/instrument.rb:16:in `instrument'
	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/base.rb:50:in `instrument'
	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/base.rb:46:in `instrument'
	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/rails2.rb:60:in `compile'
	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/rails3.rb:42:in `block in compile'
	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/instrument.rb:18:in `block (2 levels) in instrument'
	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/instrument.rb:40:in `yield_with_block_depth'
	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/instrument.rb:17:in `block in instrument'
	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/vendor/ruby/heroku-20/lib/ruby/2.6.0/benchmark.rb:308:in `realtime'
	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/instrument.rb:16:in `instrument'
	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/base.rb:50:in `instrument'
	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/base.rb:46:in `instrument'
	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/rails3.rb:41:in `compile'
	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/rails4.rb:35:in `block in compile'
	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/instrument.rb:18:in `block (2 levels) in instrument'
	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/instrument.rb:40:in `yield_with_block_depth'
	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/instrument.rb:17:in `block in instrument'
	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/vendor/ruby/heroku-20/lib/ruby/2.6.0/benchmark.rb:308:in `realtime'
	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/instrument.rb:16:in `instrument'
	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/base.rb:50:in `instrument'
	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/base.rb:46:in `instrument'
	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/rails4.rb:34:in `compile'
	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/rails6.rb:20:in `block in compile'
	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/instrument.rb:18:in `block (2 levels) in instrument'
	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/instrument.rb:40:in `yield_with_block_depth'
	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/instrument.rb:17:in `block in instrument'
	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/vendor/ruby/heroku-20/lib/ruby/2.6.0/benchmark.rb:308:in `realtime'
	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/instrument.rb:16:in `instrument'
	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/base.rb:50:in `instrument'
	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/base.rb:46:in `instrument'
	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/rails6.rb:18:in `compile'
	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/bin/support/ruby_compile:20:in `block (2 levels) in <main>'
	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/base.rb:190:in `log'
	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/bin/support/ruby_compile:19:in `block in <main>'
	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/instrument.rb:35:in `block in trace'
	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/instrument.rb:18:in `block (2 levels) in instrument'
	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/instrument.rb:40:in `yield_with_block_depth'
	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/instrument.rb:17:in `block in instrument'
	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/vendor/ruby/heroku-20/lib/ruby/2.6.0/benchmark.rb:308:in `realtime'
	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/instrument.rb:16:in `instrument'
	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/instrument.rb:35:in `trace'
	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/bin/support/ruby_compile:15:in `<main>'
 !     Push rejected, failed to compile Ruby app.
 !     Push failed
```

**Comment by BerkhanBerkdemir** [comment]
Do you have any updates on this bug report, @johnbumgardner?

**Comment by steveyken** [comment]
The error message says that it can't find "lib-node-v8..." However, that
gem is being installed earlier in the build process so this feels like an
environment setup issue.

Can you double check you are using 'bundle exec rake ...' style commands?
As you'll no doubt know, 'bundle exec' helps to build the correct
environment to execute the rake tasks in.

I'm afraid I don't have any experience with buildpacks on heroku.

**Comment by johnbumgardner** [comment]
try running this command
gem install libv8 -v '15.14.0.1' -- --with-system-v8

**Comment by johnbumgardner** [comment]
I realize this has been a while, but I'm going to revisit this @BerkhanBerkdemir

**Comment by johnbumgardner** [comment]
I followed the steps exactly, and I encountered no errors.

**Comment by BerkhanBerkdemir** [comment]
> I followed the steps exactly, and I encountered no errors.

I also followed the steps and I finally make it work on Heroku. I used `heroku-20` and I only and manually set up `HEROKU=true` environment variable, added PostgreSQL add-on. Then I pushed the branch with Git over SSH and I was able to see that FFC is running.

Thank you @johnbumgardner for letting me know.
