### ISSUE TITLE
Couldn't find Active Storage configuration in /app/config/storage.yml

### ISSUE THREAD

**Issue by samueladesoga** [fatfreecrm/fat_free_crm#993]
I have installed fat free crm to heroku following the instruction and i get this error in the log files

Couldn't find Active Storage configuration in /app/config/storage.yml

Am i missing something?

**Comment by rinshadka** [comment]
Hi,

Same issue for me too. I am deploying in docker and the same version **v0.20.0** deployed earlier in development server without issues.

```
=> Booting Puma
=> Rails 6.1.7 application starting in production
=> Run `bin/rails server --help` for more startup options
Exiting
/usr/local/bundle/gems/activestorage-6.1.7/lib/active_storage/engine.rb:137:in `block (2 levels) in <class:Engine>': Couldn't find Active Storage configuration in /fat_free_crm/config/storage.yml (RuntimeError)
        from /usr/local/bundle/gems/activesupport-6.1.7/lib/active_support/lazy_load_hooks.rb:71:in `class_eval'
        from /usr/local/bundle/gems/activesupport-6.1.7/lib/active_support/lazy_load_hooks.rb:71:in `block in execute_hook'
        from /usr/local/bundle/gems/activesupport-6.1.7/lib/active_support/lazy_load_hooks.rb:61:in `with_execution_control'
        from /usr/local/bundle/gems/activesupport-6.1.7/lib/active_support/lazy_load_hooks.rb:66:in `execute_hook'
        from /usr/local/bundle/gems/activesupport-6.1.7/lib/active_support/lazy_load_hooks.rb:52:in `block in run_load_hooks'
        from /usr/local/bundle/gems/activesupport-6.1.7/lib/active_support/lazy_load_hooks.rb:51:in `each'
        from /usr/local/bundle/gems/activesupport-6.1.7/lib/active_support/lazy_load_hooks.rb:51:in `run_load_hooks'
        from /usr/local/bundle/gems/activestorage-6.1.7/app/models/active_storage/blob.rb:354:in `<main>'
        from /usr/local/bundle/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from /usr/local/bundle/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from /usr/local/bundle/gems/zeitwerk-2.6.0/lib/zeitwerk/kernel.rb:27:in `require'
        from /usr/local/bundle/gems/zeitwerk-2.6.0/lib/zeitwerk/loader/helpers.rb:127:in `const_get'
        from /usr/local/bundle/gems/zeitwerk-2.6.0/lib/zeitwerk/loader/helpers.rb:127:in `cget'
        from /usr/local/bundle/gems/zeitwerk-2.6.0/lib/zeitwerk/loader.rb:246:in `block (2 levels) in eager_load'
```
